#!/bin/sh
flist=filelist
crctool_folder=.tools
crctool=$crctool_folder/crc32
rm -f $flist


make -C $crctool_folder clean
make -C $crctool_folder

for file in $(git ls-files)
do
	if [ $file != $flist ] && [[ $file != $crctool_folder* ]]
	then
		echo -en "$(./$crctool $file)\n" >> $flist
	fi
done

cat $flist
make -C $crctool_folder clean

git add $flist